name: Automatic Release
on:
  push:
    branch:
      - main
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
      - name: install dependencies and build
        run: npm install
      - name: build
        run: npm run build
      - name: deploy to firebase hosting
        run: firebase deploy --token $GCP_SA_KEY
        env:
          GCP_SA_KEY: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
